import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const firaCode = Fira_Code({
  variable: "--font-fira-code", // Store the font in a CSS variable
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Specify available weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.variable} antialiased`}>
        <div className="max-w-screen-xl mx-auto bg-background min-h-screen">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
